on:
  push:
  pull_request:
name: CI
jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: flathub-infra/flatpak-github-actions/flatpak-builder@23796715b3dfa4c86ddf50cf29c3cc8b3c82dca8
        with:
          bundle: cinder.flatpak
          manifest-path: com.avojak.cinder.yml
          cache-key: "flatpak-builder-${{ github.sha }}"